language: python

python:
  - 2.7

sudo: false

cache:
  apt: true

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - gfortran-4.9
      - cmake
      - cmake-data
      - hdf5-tools 
      - libhdf5-serial-dev

before_install:
  - pip install codecov
  - git submodule update --init --recursive

install:
  - export FC=/usr/bin/gfortran-4.9
  - $FC --version
  - cmake --version

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - ctest -VV -T Start -T Build -T Test -T Coverage

after_success:
  - find . -name '*.gcno' -print
  - gcov-4.9 --version
  - bash <(curl -s https://codecov.io/bash) -x $(which gcov-4.9)

after_script:
  - cd ..
  - rm -rf build

os:
  - linux
